import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillFacebook,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import bart from "../public/av2.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/benton-roofing.png";
import web2 from "../public/mobilebrochure.png";
import web3 from "../public/chemp-2.png";
import web4 from "../public/flymart.png";
import web5 from "../public/ecg.png";
import web6 from "../public/blueridgefloors.png";
import Cta from "../components/cta";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">BartelZandstra</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://my.indeed.com/p/bartelz-vuwolpj"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Bartel Zandstra
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Front-End Developer & SEO Specialist
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Helping businesses succeed with SEO-optimized web applications
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href='https://www.linkedin.com/in/bartel-zandstra-935848165/'>
              <AiFillLinkedin/>
              </a>
              <a href='https://twitter.com/BartelZandstra'>
              <AiFillTwitterCircle  />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={bart} layout="fill" objectFit="cover" alt='avatar version of me'/>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since 2015, I have been in love with digital marketing.  Google Ads, Social Media, SEO, all of it.  I love the competitive nature of digital marketing, one business trying to outrank another.  However, I decided to focus on building websites in an SEO-optimized way as my specialty, studying website builders like Wordpress and Wix, front end technologies like React, and also studying SEO best practices. Most of my experience at this point comes from self-obtained knowledge and picking up projects on my own.  I have spent most of my years working in the restaurant industry, mainly in kitchens.  However, along my journey, I've gained incredible knowledge, and have developed valuable skills.  I obtained a digital media certificate from my local community college AB-Tech, where I learned how to effectively use design tools like Adobe Illustrator, Photoshop, and Figma.  I can code effectively in      
              <span className="text-teal-500"> HTML, CSS, and JS. </span>
              I am knowledgable with <span className="text-teal-500">Wordpress, PHP, Create React App, NextJS, and GatsbyJS. </span>  In the little free time I have, I like to go disc golfing "frisbee golf", "frolf" during the day, or perhaps attend a concert in the evening.
            </p>
            
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt='designs logo'/>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Canva</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt='coding logo'/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Coding
              </h3>
              <p className="py-2">
               Utilizing front end web technologies to engineer incredible user experiences
              </p>
              <h4 className="py-4 text-teal-600">Languages I Code In</h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">Javescipt</p>
              <p className="text-gray-800 py-1">PHP</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} alt='seo logo'/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">SEO</h3>
              <p className="py-2">
                Onsite optimization and content creation for off-site SEO
              </p>
              <h4 className="py-4 text-teal-600">SEO Tools I've Used</h4>
              <p className="text-gray-800 py-1">Ahrefs</p>
              <p className="text-gray-800 py-1">SemRush</p>
              <p className="text-gray-800 py-1">Moz Pro</p>
              <p className="text-gray-800 py-1">Agency Analytics</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
             When I think of SEO for web development, I think of a few things: 
             <span className="text-teal-500"> structured data, quality content , alt tags, meta descriptions, proper HTML semantic tags, website structure, including a robots.txt file, internal links </span>
              ,  did I miss anything?  I probably did.  Humans usually do.  That's why I rely on my favorite SEO tools to do a website audit.  I personally like   
              <span className="text-teal-500"> Ahrefs. </span>
              
              I check the results of my Ahrefs audit and clean up anything I missed.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Here are a few projects I've collaborated on..
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a href='https://bentonroofing.com/'>
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                alt='company 1'
              /></a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://www.mobilebrochure.com/'>
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                alt='company 2'
              /></a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://carolinahempcompany.com/'>
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
                alt='company 3'
              /></a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://www.discgolfflymart.com/'>
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                alt='company 4'
              /></a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='http://eastcoast-granite.com/'>
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                alt='company 5'
              /></a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href='https://www.floorsnc.com/'>
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                alt='company 6'
              /></a>
            </div>
          </div>
          <Cta />
        </section>
  
      </main>
    </div>
  );
}
